### ISSUE TITLE
添加新的模板出错

### ISSUE THREAD

**Issue by daleqq** [lotabout/CodeGenerator#11]
使用新添加的模板后提示错误
````
org.jetbrains.java.generate.exception.GenerateCodeException: Error in Velocity code generator
Caused by: Invocation of method 'sanitizeJavaIdentifier' in  class java.lang.Class threw exception java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/intellij/openapi/util/text/StringUtil.sanitizeJavaIdentifier must not be null at me.lotabout.codegenerator.util.GenerationUtil[line 10, column 71]
	at me.lotabout.codegenerator.util.GenerationUtil.velocityEvaluate(GenerationUtil.java:144)
	at me.lotabout.codegenerator.worker.JavaBodyWorker.execute(JavaBodyWorker.java:35)
	at me.lotabout.codegenerator.action.CodeGeneratorAction.actionPerformed(CodeGeneratorAction.java:120)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:203)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:191)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:185)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$8(AbstractPopup.java:1405)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3078)
```

* IntelliJ版本：2018.2

**Comment by daleqq** [comment]
找到出错的地方了
```
$StringUtil.sanitizeJavaIdentifier($helper.getPropertyName($field.element, $project))))
```
在这个插件中应该使用`$field.element`, 而IntelliJ的模板中使用的是`$(field)`
